/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.management.system;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*; 

/**
 *
 * @author buhle
 */
public class StudentForm extends javax.swing.JFrame {
    
    DefaultTableModel model;
    private final String FILE_NAME = "sudents.txt";
    private Object[] lastDeletedStudent; // Stores the entire row
    private int lastDeletedRow = -1; // Rememebers where the student was in the table
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentForm.class.getName());

    /**
     * Creates new form StudentForm
     */
    public StudentForm() { // Constructor
        initComponents();
        
        model = (DefaultTableModel) tblStudent.getModel();
        
        loadStudents();
        
        // So that the colors can display on the output
        btnAdd.setBackground(new java.awt.Color(0, 153, 51));  // Green
btnAdd.setForeground(java.awt.Color.WHITE);

btnDelete.setBackground(new java.awt.Color(204, 0, 0));    // Red
btnDelete.setForeground(java.awt.Color.WHITE);

btnUpdate.setBackground(new java.awt.Color(255, 153, 0));  // Orange
btnUpdate.setForeground(java.awt.Color.WHITE);

btnSearch.setBackground(new java.awt.Color(0, 102, 204));  // Blue
btnSearch.setForeground(java.awt.Color.WHITE);

btnClear.setBackground(new java.awt.Color(102, 102, 102)); // Grey
btnClear.setForeground(java.awt.Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student Management System");

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Student ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Course:");

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Business Intelligence", "Data Science", "Cyber Security", "Cloud Computing", "Information Technology", "Internet of Things", "Software Development" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStudentID)
                    .addComponent(txtFirstName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail)
                    .addComponent(cmbCourse, 0, 246, Short.MAX_VALUE))
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(java.awt.SystemColor.activeCaption);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Email", "Course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        btnAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/add.png"))); // NOI18N
        btnAdd.setText(" Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnUpdate.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnUndo.setBackground(new java.awt.Color(204, 0, 255));
        btnUndo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/management/system/undo-removebg-preview.png"))); // NOI18N
        btnUndo.setText("Undo");
        btnUndo.addActionListener(this::btnUndoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnAdd)
                .addGap(53, 53, 53)
                .addComponent(btnUpdate)
                .addGap(51, 51, 51)
                .addComponent(btnDelete)
                .addGap(54, 54, 54)
                .addComponent(btnClear)
                .addGap(55, 55, 55)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnUndo)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnSearch)
                    .addComponent(btnUndo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ADD BUTTON
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // When a user types "ABC123" this prevents the program from crashing
        int studentid;
        try {
        
        studentid = Integer.parseInt(txtStudentID.getText());
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "Student ID must be a number.");
            
            return;
        }
        // Check for duplicate student ids
        for (int i = 0; i < model.getRowCount(); i++) {
            
            if(Integer.parseInt(model.getValueAt(i, 0).toString()) == studentid) {
                
                JOptionPane.showMessageDialog(this, "Student ID already exists");
                
                return;
            }
        }
        // Validate email
        if (!txtEmail.getText().contains("@")) {
            
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
            
            return;
        }
        if (txtStudentID.getText().trim().isEmpty() ||
            txtFirstName.getText().trim().isEmpty() ||
            txtLastName.getText().trim().isEmpty() ||
            txtEmail.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            // When validation fails, this will immediately stop the method
            return;
        }
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String email = txtEmail.getText();
        String course = cmbCourse.getSelectedItem().toString();
        
        model.addRow(new Object[]
                {
                    studentid,
                    firstName,
                    lastName,
                    email,
                    course
                });
        // Save all students to the text file
        saveStudents();
    }//GEN-LAST:event_btnAddActionPerformed
// CLEAR BUTTON
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        ClearFields();
    }//GEN-LAST:event_btnClearActionPerformed
// DELETE BUTTON
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // Delete the selected row
        int row = tblStudent.getSelectedRow();
        // Clear the text fields
        if(row >= 0){
            lastDeletedStudent = new Object[model.getColumnCount()];
            
            for (int i = 0; i < model.getColumnCount(); i++) {
                lastDeletedStudent[i] = model.getValueAt(row, i);
            }
            
            lastDeletedRow = row;
            
            model.removeRow(row);
            
            saveStudents();
            
            ClearFields();
            
        } else {
            // Show a message if nothing is selected
            JOptionPane.showMessageDialog(this, "Please select a student to delete");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // UPDATE BUTTON
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Find the selected row
        int row = tblStudent.getSelectedRow();
        // Check if a row was selected
        if(row >= 0) {
            // Update 
            model.setValueAt(txtStudentID.getText(), row, 0);
            model.setValueAt(txtFirstName.getText(), row, 1);
            model.setValueAt(txtLastName.getText(), row, 2);
            model.setValueAt(txtEmail.getText(), row, 3);
            model.setValueAt(cmbCourse.getSelectedItem(), row, 4);
            
            // Display success message if studen is found
            JOptionPane.showMessageDialog(this, "Student updated successfully");
            saveStudents();
        } else {
            // If the student is not found display this message
            JOptionPane.showMessageDialog(this, "Please select a student to update.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
// SEARCH BUTTON
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        // Getting text from the Student ID textbox
        String id = txtStudentID.getText();
        
        // Assumption that studenr doesn't exixt, however if they exist it will become true
        boolean found = false;
        // Looping through every row
        for(int i = 0; i < model.getRowCount(); i++) {
            // Comparing the Student IDs
            if(model.getValueAt(i,0).toString().equals(id)) {
                tblStudent.setRowSelectionInterval(i,i);
                // Filling in the textboxes
                txtFirstName.setText(model.getValueAt(i,1).toString());
                txtLastName.setText(model.getValueAt(i,2).toString());
                txtEmail.setText(model.getValueAt(i,3).toString());
                cmbCourse.setSelectedItem(model.getValueAt(i,4).toString());
                // Student is found
                found = true;
                // Stop searching
                break;
            }
        }
        // If student is not found display message
        if(!found) {
            JOptionPane.showMessageDialog(this, "Student not found");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        // Check if there is something to undo
        if (lastDeletedStudent != null) {
            // Put the student back
            model.insertRow(lastDeletedRow, lastDeletedStudent);
            // Save the updated table
            saveStudents();
            
            JOptionPane.showMessageDialog(this, "Last deleted student restored.");
            
            // Clear the saved information
            lastDeletedStudent = null;
            lastDeletedRow = -1;
        } else {
            
            JOptionPane.showMessageDialog(this, "Nothing to undo");
        }
    }//GEN-LAST:event_btnUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentForm().setVisible(true));
    }
    private void ClearFields()
    {
        txtStudentID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        
        txtStudentID.requestFocus();
    }
    
    private void saveStudents() {
        try{
            // Creates the file
            PrintWriter writer = new PrintWriter(new FileWriter(FILE_NAME));
            // Loop through every student in the table
            for (int i = 0; i < model.getRowCount(); i++) {
                // Writes one student per line then goes on the next line
                writer.println(
                model.getValueAt(i, 0) + "," +
                model.getValueAt(i, 1) + "," +
                model.getValueAt(i, 2) + "," +
                model.getValueAt(i, 3) + "," +
                model.getValueAt(i, 4)
                );
            }
            writer.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving file.");
        }
    }
    
    private void loadStudents() {
        try {
            
            BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME));
            
            String line;
            
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                model.addRow(data);
            }
            reader.close();
        } catch (IOException e) {
            // It will ignore if file doesn't exist
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUndo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
